title : Battlegrounds
tagline: Live Gaming Experience
contact:
  email : contact@battlegrounds.net
  twitter: battlegroundsHQ
  facebook: battlegroundsHQ

markdown: redcarpet
pygments: true
permalink: /:title

