title : Battlegrounds
tagline: Live Action Gaming
contact:
  email : contact@battlegrounds.net
  twitter: battlegroundsHQ
  facebook: battlegroundsHQ

markdown: redcarpet
pygments: true
permalink: /:title

