title : Battlegrounds
tagline: Live Gaming Experience
contact:
  email : contact@battlegrounds.net
  twitter: battlegroundsHQ
  facebook: battlegroundsHQ
googleanalytics: UA-44676956-1
basepath: '/'

markdown: redcarpet
highlighter: true
permalink: /:title

